name: Generate Dynamic README

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Generate README
        run: |
          echo "# ozanozzz.github.io" > README.md

          if [[ -f "style.css" ]]; then
            echo "## Style.css" >> README.md
            echo '```css' >> README.md
            cat style.css >> README.md
            echo '```' >> README.md
            echo "" >> README.md
          fi

          if [[ -f "main.js" ]]; then
            echo "## Main.js" >> README.md
            echo '```javascript' >> README.md
            cat main.js >> README.md
            echo '```' >> README.md
            echo "" >> README.md
          fi

          if [[ -f "index.html" ]]; then
            echo "## index.html" >> README.md
            echo '```html' >> README.md
            cat index.html >> README.md
            echo '```' >> README.md
            echo "" >> README.md
          fi

      - name: Add and Commit Changes (if any)
        run: |
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes detected in README.md"
          else
            git commit -m "Update README with code snippets"
            git pull origin main
            git push origin main
          fi