name: Generate README

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generate README
        run: |
          # Overwrite existing README.md
          echo "# ozanozzz.github.io" > README.md
          echo "visit the [Test Mutecity](https://ozanozzz.github.io)." >> README.md
          echo "" >> README.md  # Add a newline for separation

          # Check if style.css exists and add its content
          if [ -f style.css ]; then
            echo "## Style.css" >> README.md
            echo '```css' >> README.md
            cat style.css >> README.md
            echo '```' >> README.md
            echo "" >> README.md  # Add a newline for separation
          fi

          # Check if main.js exists and add its content
          if [ -f main.js ]; then
            echo "## Main.js" >> README.md
            echo '```javascript' >> README.md
            cat main.js >> README.md
            echo '```' >> README.md
            echo "" >> README.md  # Add a newline for separation
          fi

          # Check if index.html exists and add its content
          if [ -f index.html ]; then
            echo "## index.html" >> README.md
            echo '```html' >> README.md
            cat index.html >> README.md
            echo '```' >> README.md
          fi

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README.md with latest file contents" || echo "No changes to commit"
          git push
